In [1]:
import numpy as np
import pandas as pd

In [3]:
trip_data=pd.read_csv('AGG-20150407.csv')
atri_data=pd.read_csv('BEJ201504_3hours.csv')
shop_data=pd.read_csv('shopName_2015.csv')
line5_traveler_data=pd.read_csv('5line_data')

In [4]:
trip_data

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,134,135,136,137,138,139,140,141,142,143
0,startTime,2015-04-07 00:00:00,2015-04-07 00:10:00,2015-04-07 00:20:00,2015-04-07 00:30:00,2015-04-07 00:40:00,2015-04-07 00:50:00,2015-04-07 01:00:00,2015-04-07 01:10:00,2015-04-07 01:20:00,...,2015-04-07 22:20:00,2015-04-07 22:30:00,2015-04-07 22:40:00,2015-04-07 22:50:00,2015-04-07 23:00:00,2015-04-07 23:10:00,2015-04-07 23:20:00,2015-04-07 23:30:00,2015-04-07 23:40:00,2015-04-07 23:50:00
1,endTime,2015-04-07 00:10:00,2015-04-07 00:20:00,2015-04-07 00:30:00,2015-04-07 00:40:00,2015-04-07 00:50:00,2015-04-07 01:00:00,2015-04-07 01:10:00,2015-04-07 01:20:00,2015-04-07 01:30:00,...,2015-04-07 22:30:00,2015-04-07 22:40:00,2015-04-07 22:50:00,2015-04-07 23:00:00,2015-04-07 23:10:00,2015-04-07 23:20:00,2015-04-07 23:30:00,2015-04-07 23:40:00,2015-04-07 23:50:00,2015-04-08 00:00:00
2,111_in,0,0,0,0,0,0,0,0,0,...,32,1,0,1,1,1,0,0,0,0
3,111_out,69,67,0,0,0,0,0,0,0,...,284,393,312,274,156,107,86,38,0,0
4,112_in,0,0,0,0,0,0,0,0,0,...,1,2,1,1,0,0,2,0,0,0
5,112_out,9,2,0,0,0,0,0,0,0,...,61,41,61,25,17,17,18,6,0,0
6,113_in,0,0,0,0,0,0,0,0,0,...,25,10,2,2,0,2,1,0,0,0
7,113_out,40,0,0,0,0,0,0,0,0,...,289,127,313,140,97,63,30,16,0,0
8,114_in,0,0,0,0,0,0,0,0,0,...,8,4,2,0,1,1,0,0,0,0
9,114_out,6,0,0,0,0,0,0,0,0,...,99,40,127,39,36,29,27,0,0,0
10,115_in,0,0,0,0,0,0,0,0,0,...,16,20,2,1,0,0,1,0,0,0
11,115_out,0,0,0,0,0,0,0,0,0,...,98,93,49,37,16,12,17,0,0,0
12,116_in,0,0,0,0,0,0,0,0,0,...,23,20,7,2,2,3,0,0,0,0
13,116_out,0,0,0,0,0,0,0,0,0,...,105,84,78,42,24,25,9,0,0,0
14,117_in,0,0,0,0,0,0,0,0,0,...,14,11,4,4,3,0,0,0,0,0
15,117_out,0,0,0,0,0,0,0,0,0,...,51,64,36,19,14,19,1,0,0,0
16,118_in,0,0,0,0,0,0,0,0,0,...,405,81,54,17,4,4,0,0,0,0
17,118_out,0,0,0,0,0,0,0,0,0,...,64,42,21,39,17,15,0,0,0,0
18,119_in,0,0,0,0,0,0,0,0,0,...,19,30,19,4,3,4,0,0,0,0
19,119_out,0,0,0,0,0,0,0,0,0,...,18,17,16,8,5,5,0,0,0,0
20,120_in,0,0,0,0,0,0,0,0,0,...,28,20,12,12,2,0,0,0,0,0
21,120_out,0,0,0,0,0,0,0,0,0,...,16,13,10,8,8,5,0,0,0,0
22,121_in,0,0,0,0,0,0,0,0,0,...,218,146,100,48,17,0,0,0,0,0
23,121_out,0,0,0,0,0,0,0,0,0,...,50,43,36,22,9,6,0,0,0,0
24,122_in,0,0,0,0,0,0,0,0,0,...,129,82,88,33,8,0,0,0,0,0
25,122_out,0,0,0,0,0,0,0,0,0,...,38,35,45,22,12,0,0,0,0,0
26,123_in,0,0,0,0,0,0,0,0,0,...,147,111,51,42,17,0,0,0,0,0
27,123_out,220,0,0,0,0,0,0,0,0,...,51,57,52,42,64,64,6,71,0,62
28,124_in,0,0,0,0,0,0,0,0,0,...,30,19,17,10,2,0,0,0,0,0
29,124_out,0,0,0,0,0,0,0,0,0,...,73,61,45,34,15,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,1326_in,0,0,0,0,0,0,0,0,0,...,18,4,0,0,0,0,0,0,0,0
599,1326_out,0,0,0,0,0,0,0,0,0,...,24,28,23,0,0,0,0,0,0,0
600,1327_in,0,0,0,0,0,0,0,0,0,...,38,5,0,0,0,0,0,0,0,0
601,1327_out,0,0,0,0,0,0,0,0,0,...,40,23,0,0,0,0,0,0,0,0
602,1329_in,0,0,0,0,0,0,0,0,0,...,6,2,0,0,0,0,0,0,0,0
603,1329_out,0,0,0,0,0,0,0,0,0,...,12,15,0,0,0,0,0,0,0,0
604,1621_in,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
605,1621_out,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
606,1622_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
607,1622_out,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608,1624_in,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
609,1624_out,0,0,0,0,0,0,0,0,0,...,2,0,0,2,0,0,0,0,0,0
610,1625_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
611,1625_out,0,0,0,0,0,0,0,0,0,...,77,2,1,0,0,0,0,0,0,0
612,1626_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
613,1626_out,0,0,0,0,0,0,0,0,0,...,6,1,1,0,0,0,0,0,0,0
614,1627_in,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
615,1627_out,0,0,0,0,0,0,0,0,0,...,3,30,0,0,0,0,0,0,0,0
616,1628_in,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
617,1628_out,0,0,0,0,0,0,0,0,0,...,24,12,0,0,0,0,0,0,0,0
618,1629_in,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
619,1629_out,0,0,0,0,0,0,0,0,0,...,0,52,53,0,0,0,0,0,0,0
620,1630_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
621,1630_out,0,0,0,0,0,0,0,0,0,...,2,1,3,4,0,0,0,0,0,0
622,1631_in,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
623,1631_out,0,0,0,0,0,0,0,0,0,...,0,9,14,0,5,0,0,0,0,0
624,1632_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
625,1632_out,0,0,0,0,0,0,0,0,0,...,12,9,1,8,7,1,0,0,0,0
626,1633_in,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
627,1633_out,0,0,0,0,0,0,0,0,0,...,16,0,12,1,6,3,0,0,0,0

In [5]:
atri_data

,Unnamed: 0,Date,UTC time,Temp. (ºC),Rel. Hum. (%),Pressure/ Geopot.,Wind dir,Wins speed (Km/h),Clouds,Low clouds,Medium clouds,High clouds,Prec. (mm),Max temp. (ºC),Min temp. (ºC),Conditions
0,0,01/05/2015,5,15.8,87%,1013.7 Hpa,140º (SE),10.8,N/A,-,-,-,-,-,-,mist
1,1,01/05/2015,2,15.6,89%,1013.8 Hpa,110º (E ),7.2,N/A,-,-,-,-,25.4,-,mist
2,2,30/04/2015,23,16.0,86%,1014.9 Hpa,090º (E ),10.8,N/A,-,-,-,-,-,-,-
3,3,30/04/2015,20,18.0,73%,1014.3 Hpa,090º (E ),10.8,0/8,-,-,-,-,-,-,Clear
4,4,30/04/2015,17,21.3,72%,1013.1 Hpa,090º (E ),10.8,2/8,2/8 N/A,NaN,NaN,-,-,-,"Few clouds, mist"
5,5,30/04/2015,14,25.0,50%,1013.3 Hpa,320º (NW),3.6,2/8,2/8 N/A,NaN,NaN,-,-,13.8,Few clouds
6,6,30/04/2015,11,23.5,55%,1014.8 Hpa,360º (N ),7.2,5/8,5/8 N/A,NaN,NaN,-,-,-,Cloudy
7,7,30/04/2015,8,19.2,78%,1015.2 Hpa,290º (W ),10.8,0/8,0/8 CB,-,CI,-,-,-,"Clear, mist"
8,8,30/04/2015,5,13.8,94%,1013.9 Hpa,calm.,NaN,N/A,-,-,-,-,-,-,mist
9,9,30/04/2015,2,15.0,91%,1013.4 Hpa,270º (W ),7.2,N/A,-,-,-,-,19.0,-,mist
10,10,29/04/2015,23,16.2,86%,1014.3 Hpa,270º (W ),3.6,N/A,-,-,-,-,-,-,mist
11,11,29/04/2015,20,17.8,80%,1014.3 Hpa,360º (N ),7.2,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, mist"
12,12,29/04/2015,17,18.8,73%,1013.3 Hpa,290º (W ),10.8,7/8,7/8 N/A,NaN,NaN,-,-,-,Cloudy
13,13,29/04/2015,14,18.3,78%,1013.0 Hpa,290º (W ),18.0,8/8,8/8 N/A,NaN,NaN,-,-,16.3,Overcast
14,14,29/04/2015,11,16.7,84%,1014.1 Hpa,320º (NW),14.4,8/8,8/8 N/A,NaN,NaN,-,-,-,Overcast
15,15,29/04/2015,8,17.2,86%,1012.2 Hpa,020º (N),10.8,8/8,0/8 SC,AC,CI,21.0(12h),-,-,"Overcast, mist"
16,16,29/04/2015,5,17.0,89%,1010.0 Hpa,040º (NE),10.8,N/A,-,-,-,21.2(24h),-,-,mist
17,17,29/04/2015,2,17.2,90%,1007.4 Hpa,180º (S ),7.2,N/A,-,-,-,21.0(6h),30.7,-,mist
18,18,28/04/2015,23,17.5,90%,1011.7 Hpa,360º (N ),10.8,N/A,-,-,-,-,-,-,rain
19,19,28/04/2015,20,19.2,81%,1008.3 Hpa,090º (E ),10.8,0/8,-,-,-,-,-,-,"Clear, mist"
20,20,28/04/2015,17,28.6,43%,1006.6 Hpa,020º (N),10.8,0/8,-,-,-,-,-,-,Clear
21,21,28/04/2015,14,30.1,37%,1006.4 Hpa,320º (NW),14.4,0/8,-,-,-,-,-,19.2,Clear
22,22,28/04/2015,11,27.6,51%,1008.2 Hpa,270º (W ),18.0,0/8,-,-,-,-,-,-,Clear
23,23,28/04/2015,8,22.9,65%,1008.4 Hpa,220º (SW),18.0,0/8,5/8 ST,-,CI,-,-,-,"Clear, haze"
24,24,28/04/2015,5,20.3,73%,1007.4 Hpa,200º (S ),7.2,N/A,-,-,-,-,-,-,-
25,25,28/04/2015,2,19.3,81%,1007.8 Hpa,180º (S ),10.8,N/A,-,-,-,-,26.1,-,mist
26,26,27/04/2015,23,20.2,75%,1009.5 Hpa,180º (S ),14.4,N/A,-,-,-,-,-,-,mist
27,27,27/04/2015,20,21.3,66%,1010.6 Hpa,140º (SE),10.8,6/8,6/8 N/A,NaN,NaN,-,-,-,Cloudy
28,28,27/04/2015,17,24.4,52%,1010.5 Hpa,140º (SE),10.8,7/8,7/8 N/A,NaN,NaN,-,-,-,Cloudy
29,29,27/04/2015,14,25.5,48%,1011.6 Hpa,180º (S ),14.4,0/8,-,-,-,-,-,18.2,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,210,04/04/2015,23,14.6,90%,1013.8 Hpa,020º (N),7.2,N/A,-,-,-,-,-,-,mist
211,211,04/04/2015,20,15.2,87%,1014.2 Hpa,250º (W ),7.2,N/A,-,-,-,-,-,-,mist
212,212,04/04/2015,17,16.9,83%,1010.0 Hpa,320º (NW),3.6,N/A,-,-,-,-,-,-,mist
213,213,04/04/2015,14,16.9,83%,1008.0 Hpa,290º (W ),10.8,8/8,8/8 N/A,NaN,NaN,0.1(6h),-,11.5,"Overcast, mist"
214,214,04/04/2015,11,15.5,87%,1007.3 Hpa,160º (S ),7.2,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, mist"
215,215,04/04/2015,8,13.2,94%,1011.5 Hpa,250º (W ),18.0,8/8,0/8 CU,-,-,-,-,-,"Overcast, mist"
216,216,04/04/2015,5,12.7,87%,1008.1 Hpa,110º (E ),14.4,N/A,-,-,-,-,-,-,-
217,217,04/04/2015,2,12.3,83%,1009.7 Hpa,090º (E ),10.8,N/A,-,-,-,-,15.4,-,-
218,218,03/04/2015,23,11.7,81%,1012.1 Hpa,070º (E ),10.8,N/A,-,-,-,-,-,-,-
219,219,03/04/2015,20,11.6,79%,1012.6 Hpa,070º (E ),14.4,8/8,8/8 N/A,NaN,NaN,-,-,-,Overcast
220,220,03/04/2015,17,12.2,77%,1010.7 Hpa,070º (E ),14.4,8/8,8/8 N/A,NaN,NaN,-,-,-,Overcast
221,221,03/04/2015,14,12.2,80%,1010.7 Hpa,070º (E ),7.2,8/8,8/8 N/A,NaN,NaN,-,-,12.2,"Overcast, mist"
222,222,03/04/2015,11,12.5,80%,1011.5 Hpa,070º (E ),14.4,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, mist"
223,223,03/04/2015,8,12.9,80%,1009.5 Hpa,020º (N),10.8,8/8,0/8 CU/SC,AC,CC,3.0(6h),-,-,"Overcast, mist"
224,224,03/04/2015,5,13.4,83%,1006.5 Hpa,290º (W ),10.8,N/A,-,-,-,19.0(24h),-,-,mist
225,225,03/04/2015,2,15.4,90%,1004.9 Hpa,290º (W ),10.8,N/A,-,-,-,6.0(6h),31.7,-,rain
226,226,02/04/2015,23,16.9,88%,1003.6 Hpa,320º (NW),7.2,N/A,-,-,-,-,-,-,mist
227,227,02/04/2015,20,20.8,88%,1001.8 Hpa,270º (W ),14.4,8/8,8/8 N/A,NaN,NaN,10.0(6h),-,-,"Overcast, rain"
228,228,02/04/2015,17,23.5,86%,998.7 Hpa,290º (W ),21.6,N/A,-,-,-,-,-,-,rain
229,229,02/04/2015,14,30.8,49%,997.2 Hpa,180º (S ),14.4,0/8,-,-,-,-,-,15.1,Clear
230,230,02/04/2015,11,28.2,54%,1000.0 Hpa,180º (S ),14.4,0/8,-,-,-,-,-,-,Clear
231,231,02/04/2015,8,22.1,67%,1001.6 Hpa,160º (S ),14.4,3/8,6/8 CU,-,CI,-,-,-,Scattered clouds
232,232,02/04/2015,5,17.8,88%,1002.0 Hpa,140º (SE),3.6,N/A,-,-,-,-,-,-,-
233,233,02/04/2015,2,16.5,96%,1004.2 Hpa,110º (E ),10.8,N/A,-,-,-,-,22.9,-,mist
234,234,01/04/2015,23,16.1,96%,1007.6 Hpa,090º (E ),10.8,N/A,-,-,-,-,-,-,mist
235,235,01/04/2015,20,15.2,94%,1009.3 Hpa,090º (E ),10.8,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, mist"
236,236,01/04/2015,17,18.8,82%,1009.1 Hpa,090º (E ),14.4,2/8,2/8 N/A,NaN,NaN,-,-,-,Few clouds
237,237,01/04/2015,14,21.9,72%,1010.2 Hpa,090º (E ),14.4,2/8,2/8 N/A,NaN,NaN,-,-,17.8,Few clouds
238,238,01/04/2015,11,22.6,70%,1012.4 Hpa,070º (E ),14.4,0/8,-,-,-,-,-,-,Clear
239,239,01/04/2015,8,20.1,75%,1012.9 Hpa,090º (E ),14.4,1/8,-,-,CI,-,-,-,Few clouds

In [8]:
shop_data

     Unnamed: 0    id   name line/station
0             0   111     莘庄       01号线莘庄
1             1   112    外环路      01号线外环路
2             2   113    莲花路      01号线莲花路
3             3   114   锦江乐园     01号线锦江乐园
4             4   115   上海南站     01号线上海南站
5             5   116    漕宝路      01号线漕宝路
6             6   117  上海体育馆    01号线上海体育馆
7             7   118    徐家汇      01号线徐家汇
8             8   119    衡山路      01号线衡山路
9             9   120    常熟路      01号线常熟路
10           10   121   陕西南路     01号线陕西南路
11           11   122   黄陂南路     01号线黄陂南路
12           12   123   人民广场     01号线人民广场
13           13   124    新闸路      01号线新闸路
14           14   125    汉中路      01号线汉中路
15           15   126  上海火车站    01号线上海火车站
16           16   127   中山北路     01号线中山北路
17           17   128    延长路      01号线延长路
18           18   129  上海马戏城    01号线上海马戏城
19           19   130    汶水路      01号线汶水路
20           20   131   彭浦新村     01号线彭浦新村
21           21   132    共康路      01号线共康路
22           22   133   通河新村     01号线通河新村
23           23   134    呼兰路      01号线呼兰路
24           24   135   共富新村     01号线共富新村
25           25   136   宝安公路     01号线宝安公路
26           26   137   友谊西路     01号线友谊西路
27           27   138    富锦路      01号线富锦路
28           28   234    徐泾东      02号线徐泾东
29           29   235  虹桥火车站    02号线虹桥火车站
..          ...   ...    ...          ...
283         283  1242    宁国路      12号线宁国路
284         284  1243    隆昌路      12号线隆昌路
285         285  1244    爱国路      12号线爱国路
286         286  1245    复兴岛      12号线复兴岛
287         287  1246    东陆路      12号线东陆路
288         288  1247    巨峰路      12号线巨峰路
289         289  1248   杨高北路     12号线杨高北路
290         290  1249    金京路      12号线金京路
291         291  1250    申江路      12号线申江路
292         292  1251    金海路      12号线金海路
293         293  1321    金运路      13号线金运路
294         294  1322  金沙江西路    13号线金沙江西路
295         295  1323     丰庄       13号线丰庄
296         296  1324  祁连山南路    13号线祁连山南路
297         297  1325    真北路      13号线真北路
298         298  1326   大渡河路     13号线大渡河路
299         299  1327   金沙江路     13号线金沙江路
300         300  1329    武宁路      13号线武宁路
301         301  1621    龙阳路      16号线龙阳路
302         302  1622   华夏中路     16号线华夏中路
303         303  1624    周浦东      16号线周浦东
304         304  1625   鹤沙航城     16号线鹤沙航城
305         305  1626    航头东      16号线航头东
306         306  1627     新场       16号线新场
307         307  1628  野生动物园    16号线野生动物园
308         308  1629     惠南       16号线惠南
309         309  1630    惠南东      16号线惠南东
310         310  1631     书院       16号线书院
311         311  1632   临港大道     16号线临港大道
312         312  1633    滴水湖      16号线滴水湖

[313 rows x 4 columns]

In [75]:
line5_traveler_data.head(10)

,Unnamed: 0,Unnamed: 0.1,userID,inTime,inLine,inStation,outTime,outLine,outStation,transfered_inTime,transfered_outTime,dayName
0,39,0,65060,2015-04-07 18:02:07,4,鲁班路,2015-04-07 18:57:47,5,东川路,64927.0,68267.0,1
1,189,0,100254,2015-04-07 17:28:04,1,漕宝路,2015-04-07 18:16:42,5,华宁路,62884.0,65802.0,1
2,237,0,110743,2015-04-07 20:43:32,1,外环路,2015-04-07 21:13:54,5,华宁路,74612.0,76434.0,1
3,595,0,192517,2015-04-07 21:25:50,1,锦江乐园,2015-04-07 21:53:43,5,北桥,77150.0,78823.0,1
4,643,0,212799,2015-04-07 07:31:01,5,东川路,2015-04-07 07:47:28,5,文井路,27061.0,28048.0,1
5,702,0,234751,2015-04-07 06:58:12,5,北桥,2015-04-07 07:08:01,5,颛桥,25092.0,25681.0,1
6,703,0,234751,2015-04-07 16:56:00,5,颛桥,2015-04-07 17:00:47,5,北桥,60960.0,61247.0,1
7,758,0,261683,2015-04-07 18:12:05,1,新闸路,2015-04-07 18:58:55,5,颛桥,65525.0,68335.0,1
8,788,0,270672,2015-04-07 08:05:23,1,莘庄,2015-04-07 08:28:42,5,东川路,29123.0,30522.0,1
9,801,0,274219,2015-04-07 17:34:06,5,颛桥,2015-04-07 17:47:19,5,东川路,63246.0,64039.0,1

In [4]:
atri_data_0407=atri_data[atri_data['Date']=='07/04/2015']
atri_data_0407

,Unnamed: 0,Date,UTC time,Temp. (ºC),Rel. Hum. (%),Pressure/ Geopot.,Wind dir,Wins speed (Km/h),Clouds,Low clouds,Medium clouds,High clouds,Prec. (mm),Max temp. (ºC),Min temp. (ºC),Conditions
186,186,07/04/2015,23,5.3,86%,1030.8 Hpa,270º (W ),10.8,N/A,-,-,-,-,-,-,-
187,187,07/04/2015,20,5.5,83%,1030.8 Hpa,020º (N),10.8,8/8,8/8 N/A,NaN,NaN,3.0(6h),-,-,"Overcast, rain"
188,188,07/04/2015,17,8.1,66%,1028.5 Hpa,020º (N),21.6,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, rain"
189,189,07/04/2015,14,8.1,72%,1028.5 Hpa,360º (N ),10.8,8/8,8/8 N/A,NaN,NaN,0.5(6h),-,7.7,"Overcast, rain"
190,190,07/04/2015,11,8.7,65%,1027.8 Hpa,040º (NE),18.0,8/8,8/8 N/A,NaN,NaN,-,-,-,Overcast
191,191,07/04/2015,8,7.9,72%,1027.6 Hpa,020º (N),14.4,8/8,0/8 ST,AC,CI,0.5(6h),-,-,Overcast
192,192,07/04/2015,5,8.1,72%,1026.3 Hpa,020º (N),14.4,N/A,-,-,-,30.9(24h),-,-,rain
193,193,07/04/2015,2,8.0,84%,1025.8 Hpa,020º (N),18.0,N/A,-,-,-,6.0(6h),11.8,-,rain

In [5]:
atri_data_0407.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 186 to 193
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         8 non-null      int64
 1   Date               8 non-null      object
 2   UTC time           8 non-null      int64
 3   Temp. (ºC)         8 non-null      float64
 4   Rel. Hum. (%)      8 non-null      object
 5   Pressure/ Geopot.  8 non-null      object
 6   Wind dir           8 non-null      object
 7   Wins speed (Km/h)  8 non-null      float64
 8   Clouds             8 non-null      object
 9   Low clouds         8 non-null      object
 10  Medium clouds      4 non-null      object
 11  High clouds        4 non-null      object
 12  Prec. (mm)         8 non-null      object
 13  Max temp. (ºC)     8 non-null      object
 14  Min temp. (ºC)     8 non-null      object
 15  Conditions         8 non-null      object
dtypes: float64(2), int64(2), object(12)
memory usage: 1.1+ KB

In [6]:
atri_data_0407['time']=atri_data_0407['UTC time']*3600

D:\Application\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
atri_data_0407.index=[i for i in range(8)]
atri_data_0407

,Unnamed: 0,Date,UTC time,Temp. (ºC),Rel. Hum. (%),Pressure/ Geopot.,Wind dir,Wins speed (Km/h),Clouds,Low clouds,Medium clouds,High clouds,Prec. (mm),Max temp. (ºC),Min temp. (ºC),Conditions,time
0,186,07/04/2015,23,5.3,86%,1030.8 Hpa,270º (W ),10.8,N/A,-,-,-,-,-,-,-,82800
1,187,07/04/2015,20,5.5,83%,1030.8 Hpa,020º (N),10.8,8/8,8/8 N/A,NaN,NaN,3.0(6h),-,-,"Overcast, rain",72000
2,188,07/04/2015,17,8.1,66%,1028.5 Hpa,020º (N),21.6,8/8,8/8 N/A,NaN,NaN,-,-,-,"Overcast, rain",61200
3,189,07/04/2015,14,8.1,72%,1028.5 Hpa,360º (N ),10.8,8/8,8/8 N/A,NaN,NaN,0.5(6h),-,7.7,"Overcast, rain",50400
4,190,07/04/2015,11,8.7,65%,1027.8 Hpa,040º (NE),18.0,8/8,8/8 N/A,NaN,NaN,-,-,-,Overcast,39600
5,191,07/04/2015,8,7.9,72%,1027.6 Hpa,020º (N),14.4,8/8,0/8 ST,AC,CI,0.5(6h),-,-,Overcast,28800
6,192,07/04/2015,5,8.1,72%,1026.3 Hpa,020º (N),14.4,N/A,-,-,-,30.9(24h),-,-,rain,18000
7,193,07/04/2015,2,8.0,84%,1025.8 Hpa,020º (N),18.0,N/A,-,-,-,6.0(6h),11.8,-,rain,7200

In [27]:
temp=atri_data_0407['Temp. (ºC)'].tolist()
cond=atri_data_0407['Conditions'].tolist()
_temp=[]
_cond=[]

In [24]:
temp

[5.3, 5.5, 8.1, 8.1, 8.7, 7.9, 8.1, 8.0]

In [28]:
for i in range(len(line5_traveler_data.index)):
    count=7200
    if(line5_traveler_data.iloc[i,10]<7200 or line5_traveler_data.iloc[i,10]>82800):
        _temp.append(temp[0])
        _cond.append(cond[0])
    else:
        for j in range(7,0,-1):
            if(line5_traveler_data.iloc[i,10]>=count and line5_traveler_data.iloc[i,10]<=count+10800):
                _temp.append(temp[j])
                _cond.append(cond[j])
                break
            count=count+10800

In [33]:
line5_traveler_data['temp']=_temp
line5_traveler_data['conditions']=_cond

In [34]:
line5_traveler_data.head(10)

,Unnamed: 0,Unnamed: 0.1,userID,inTime,inLine,inStation,outTime,outLine,outStation,transfered_inTime,transfered_outTime,dayName,temp,conditions
0,39,0,65060,2015-04-07 18:02:07,4,鲁班路,2015-04-07 18:57:47,5,东川路,64927.0,68267.0,1,8.1,"Overcast, rain"
1,189,0,100254,2015-04-07 17:28:04,1,漕宝路,2015-04-07 18:16:42,5,华宁路,62884.0,65802.0,1,8.1,"Overcast, rain"
2,237,0,110743,2015-04-07 20:43:32,1,外环路,2015-04-07 21:13:54,5,华宁路,74612.0,76434.0,1,5.5,"Overcast, rain"
3,595,0,192517,2015-04-07 21:25:50,1,锦江乐园,2015-04-07 21:53:43,5,北桥,77150.0,78823.0,1,5.5,"Overcast, rain"
4,643,0,212799,2015-04-07 07:31:01,5,东川路,2015-04-07 07:47:28,5,文井路,27061.0,28048.0,1,8.1,rain
5,702,0,234751,2015-04-07 06:58:12,5,北桥,2015-04-07 07:08:01,5,颛桥,25092.0,25681.0,1,8.1,rain
6,703,0,234751,2015-04-07 16:56:00,5,颛桥,2015-04-07 17:00:47,5,北桥,60960.0,61247.0,1,8.1,"Overcast, rain"
7,758,0,261683,2015-04-07 18:12:05,1,新闸路,2015-04-07 18:58:55,5,颛桥,65525.0,68335.0,1,8.1,"Overcast, rain"
8,788,0,270672,2015-04-07 08:05:23,1,莘庄,2015-04-07 08:28:42,5,东川路,29123.0,30522.0,1,7.9,Overcast
9,801,0,274219,2015-04-07 17:34:06,5,颛桥,2015-04-07 17:47:19,5,东川路,63246.0,64039.0,1,8.1,"Overcast, rain"